// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"github.com/puchidemy/puchi-backend/app/notification/internal/biz"
	"github.com/puchidemy/puchi-backend/app/notification/internal/conf"
	"github.com/puchidemy/puchi-backend/app/notification/internal/data"
	"github.com/puchidemy/puchi-backend/app/notification/internal/server"
	"github.com/puchidemy/puchi-backend/app/notification/internal/service"
	"github.com/puchidemy/puchi-backend/pkg/auth"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, gotify *conf.Gotify, confAuth *conf.Auth, jwtValidator *auth.JWTValidator, logger *slog.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	todoRepo := data.NewTodoRepo(dataData)
	todoUsecase := biz.NewTodoUsecase(todoRepo)
	todoService := service.NewTodoService(todoUsecase)
	pool := dataData.Pool
	preferenceRepo := data.NewPreferenceRepo(pool)
	gotifyClient := data.NewGotifyClient(gotify)
	notificationUsecase := biz.NewNotificationUsecase(preferenceRepo, gotifyClient)
	notificationService := service.NewNotificationService(notificationUsecase)
	grpcServer := server.NewGRPCServer(confServer, todoService, notificationService)
	httpServer := server.NewHTTPServer(confServer, confAuth, jwtValidator, todoService, notificationService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
