// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"github.com/puchidemy/puchi-backend/app/core/internal/biz"
	"github.com/puchidemy/puchi-backend/app/core/internal/conf"
	"github.com/puchidemy/puchi-backend/app/core/internal/data"
	"github.com/puchidemy/puchi-backend/app/core/internal/server"
	"github.com/puchidemy/puchi-backend/app/core/internal/service"
	"github.com/puchidemy/puchi-backend/pkg/auth"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confAuth *conf.Auth, jwtValidator *auth.JWTValidator, logger *slog.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	pool := dataData.Pool
	userRepo := data.NewUserRepo(pool)
	profileUsecase := biz.NewProfileUsecase(userRepo)
	achievementRepo := data.NewAchievementRepo(pool)
	achievementUsecase := biz.NewAchievementUsecase(achievementRepo)
	statsRepo := data.NewStatsRepo(pool)
	statsUsecase := biz.NewStatsUsecase(statsRepo)
	statsService := service.NewStatsService(statsUsecase)
	profileService := service.NewProfileService(profileUsecase, achievementUsecase, statsService)
	grpcServer := server.NewGRPCServer(confServer, confAuth, profileService)
	httpServer := server.NewHTTPServer(confServer, confAuth, jwtValidator, profileService, profileUsecase)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
