// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: profile/v1/profile.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Achievement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Color         string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	Progress      int32                  `protobuf:"varint,6,opt,name=progress,proto3" json:"progress,omitempty"`
	ProgressLabel string                 `protobuf:"bytes,7,opt,name=progress_label,json=progressLabel,proto3" json:"progress_label,omitempty"`
	Unlocked      bool                   `protobuf:"varint,8,opt,name=unlocked,proto3" json:"unlocked,omitempty"`
	UnlockedAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=unlocked_at,json=unlockedAt,proto3" json:"unlocked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Achievement) Reset() {
	*x = Achievement{}
	mi := &file_profile_v1_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Achievement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Achievement) ProtoMessage() {}

func (x *Achievement) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Achievement.ProtoReflect.Descriptor instead.
func (*Achievement) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{0}
}

func (x *Achievement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Achievement) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Achievement) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Achievement) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Achievement) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Achievement) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Achievement) GetProgressLabel() string {
	if x != nil {
		return x.ProgressLabel
	}
	return ""
}

func (x *Achievement) GetUnlocked() bool {
	if x != nil {
		return x.Unlocked
	}
	return false
}

func (x *Achievement) GetUnlockedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UnlockedAt
	}
	return nil
}

type AchievementList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Achievement         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AchievementList) Reset() {
	*x = AchievementList{}
	mi := &file_profile_v1_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AchievementList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AchievementList) ProtoMessage() {}

func (x *AchievementList) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AchievementList.ProtoReflect.Descriptor instead.
func (*AchievementList) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{1}
}

func (x *AchievementList) GetItems() []*Achievement {
	if x != nil {
		return x.Items
	}
	return nil
}

type Stats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalLessons     int32                  `protobuf:"varint,1,opt,name=total_lessons,json=totalLessons,proto3" json:"total_lessons,omitempty"`
	CompletedLessons int32                  `protobuf:"varint,2,opt,name=completed_lessons,json=completedLessons,proto3" json:"completed_lessons,omitempty"`
	TotalMinutes     int32                  `protobuf:"varint,3,opt,name=total_minutes,json=totalMinutes,proto3" json:"total_minutes,omitempty"`
	Accuracy         float32                `protobuf:"fixed32,4,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	WordsLearned     int32                  `protobuf:"varint,5,opt,name=words_learned,json=wordsLearned,proto3" json:"words_learned,omitempty"`
	CurrentXp        int32                  `protobuf:"varint,6,opt,name=current_xp,json=currentXp,proto3" json:"current_xp,omitempty"`
	TotalXp          int32                  `protobuf:"varint,7,opt,name=total_xp,json=totalXp,proto3" json:"total_xp,omitempty"`
	Level            int32                  `protobuf:"varint,8,opt,name=level,proto3" json:"level,omitempty"`
	XpToNextLevel    int32                  `protobuf:"varint,9,opt,name=xp_to_next_level,json=xpToNextLevel,proto3" json:"xp_to_next_level,omitempty"`
	Streak           int32                  `protobuf:"varint,10,opt,name=streak,proto3" json:"streak,omitempty"`
	LongestStreak    int32                  `protobuf:"varint,11,opt,name=longest_streak,json=longestStreak,proto3" json:"longest_streak,omitempty"`
	StreakFreezes    int32                  `protobuf:"varint,12,opt,name=streak_freezes,json=streakFreezes,proto3" json:"streak_freezes,omitempty"`
	Crowns           int32                  `protobuf:"varint,13,opt,name=crowns,proto3" json:"crowns,omitempty"`
	Gems             int32                  `protobuf:"varint,14,opt,name=gems,proto3" json:"gems,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_profile_v1_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{2}
}

func (x *Stats) GetTotalLessons() int32 {
	if x != nil {
		return x.TotalLessons
	}
	return 0
}

func (x *Stats) GetCompletedLessons() int32 {
	if x != nil {
		return x.CompletedLessons
	}
	return 0
}

func (x *Stats) GetTotalMinutes() int32 {
	if x != nil {
		return x.TotalMinutes
	}
	return 0
}

func (x *Stats) GetAccuracy() float32 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *Stats) GetWordsLearned() int32 {
	if x != nil {
		return x.WordsLearned
	}
	return 0
}

func (x *Stats) GetCurrentXp() int32 {
	if x != nil {
		return x.CurrentXp
	}
	return 0
}

func (x *Stats) GetTotalXp() int32 {
	if x != nil {
		return x.TotalXp
	}
	return 0
}

func (x *Stats) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Stats) GetXpToNextLevel() int32 {
	if x != nil {
		return x.XpToNextLevel
	}
	return 0
}

func (x *Stats) GetStreak() int32 {
	if x != nil {
		return x.Streak
	}
	return 0
}

func (x *Stats) GetLongestStreak() int32 {
	if x != nil {
		return x.LongestStreak
	}
	return 0
}

func (x *Stats) GetStreakFreezes() int32 {
	if x != nil {
		return x.StreakFreezes
	}
	return 0
}

func (x *Stats) GetCrowns() int32 {
	if x != nil {
		return x.Crowns
	}
	return 0
}

func (x *Stats) GetGems() int32 {
	if x != nil {
		return x.Gems
	}
	return 0
}

type User struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username            string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FirstName           string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName            string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email               string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	AvatarUrl           string                 `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Bio                 string                 `protobuf:"bytes,7,opt,name=bio,proto3" json:"bio,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	OnboardingCompleted bool                   `protobuf:"varint,10,opt,name=onboarding_completed,json=onboardingCompleted,proto3" json:"onboarding_completed,omitempty"`
	AgeRange            string                 `protobuf:"bytes,11,opt,name=age_range,json=ageRange,proto3" json:"age_range,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_profile_v1_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetOnboardingCompleted() bool {
	if x != nil {
		return x.OnboardingCompleted
	}
	return false
}

func (x *User) GetAgeRange() string {
	if x != nil {
		return x.AgeRange
	}
	return ""
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	AgeRange      string                 `protobuf:"bytes,5,opt,name=age_range,json=ageRange,proto3" json:"age_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_profile_v1_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProfileRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateProfileRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateProfileRequest) GetAgeRange() string {
	if x != nil {
		return x.AgeRange
	}
	return ""
}

type UpdateAvatarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvatarKey     string                 `protobuf:"bytes,1,opt,name=avatar_key,json=avatarKey,proto3" json:"avatar_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAvatarRequest) Reset() {
	*x = UpdateAvatarRequest{}
	mi := &file_profile_v1_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAvatarRequest) ProtoMessage() {}

func (x *UpdateAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAvatarRequest.ProtoReflect.Descriptor instead.
func (*UpdateAvatarRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAvatarRequest) GetAvatarKey() string {
	if x != nil {
		return x.AvatarKey
	}
	return ""
}

type GetProfileByUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByUsernameRequest) Reset() {
	*x = GetProfileByUsernameRequest{}
	mi := &file_profile_v1_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByUsernameRequest) ProtoMessage() {}

func (x *GetProfileByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByUsernameRequest.ProtoReflect.Descriptor instead.
func (*GetProfileByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{6}
}

func (x *GetProfileByUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ListDailyActivityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// YYYY-MM-DD; defaults to 90 days ago when empty.
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// YYYY-MM-DD; defaults to today (UTC) when empty.
	To            string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDailyActivityRequest) Reset() {
	*x = ListDailyActivityRequest{}
	mi := &file_profile_v1_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDailyActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDailyActivityRequest) ProtoMessage() {}

func (x *ListDailyActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDailyActivityRequest.ProtoReflect.Descriptor instead.
func (*ListDailyActivityRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{7}
}

func (x *ListDailyActivityRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ListDailyActivityRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type DailyActivityItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Date             string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	LessonsCompleted int32                  `protobuf:"varint,2,opt,name=lessons_completed,json=lessonsCompleted,proto3" json:"lessons_completed,omitempty"`
	XpEarned         int32                  `protobuf:"varint,3,opt,name=xp_earned,json=xpEarned,proto3" json:"xp_earned,omitempty"`
	MinutesSpent     int32                  `protobuf:"varint,4,opt,name=minutes_spent,json=minutesSpent,proto3" json:"minutes_spent,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DailyActivityItem) Reset() {
	*x = DailyActivityItem{}
	mi := &file_profile_v1_profile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyActivityItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyActivityItem) ProtoMessage() {}

func (x *DailyActivityItem) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyActivityItem.ProtoReflect.Descriptor instead.
func (*DailyActivityItem) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{8}
}

func (x *DailyActivityItem) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyActivityItem) GetLessonsCompleted() int32 {
	if x != nil {
		return x.LessonsCompleted
	}
	return 0
}

func (x *DailyActivityItem) GetXpEarned() int32 {
	if x != nil {
		return x.XpEarned
	}
	return 0
}

func (x *DailyActivityItem) GetMinutesSpent() int32 {
	if x != nil {
		return x.MinutesSpent
	}
	return 0
}

type DailyActivityList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DailyActivityItem   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyActivityList) Reset() {
	*x = DailyActivityList{}
	mi := &file_profile_v1_profile_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyActivityList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyActivityList) ProtoMessage() {}

func (x *DailyActivityList) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyActivityList.ProtoReflect.Descriptor instead.
func (*DailyActivityList) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{9}
}

func (x *DailyActivityList) GetItems() []*DailyActivityItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListWeeklyXPRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of weeks to return; defaults to 12.
	Weeks         int32 `protobuf:"varint,1,opt,name=weeks,proto3" json:"weeks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWeeklyXPRequest) Reset() {
	*x = ListWeeklyXPRequest{}
	mi := &file_profile_v1_profile_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWeeklyXPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWeeklyXPRequest) ProtoMessage() {}

func (x *ListWeeklyXPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWeeklyXPRequest.ProtoReflect.Descriptor instead.
func (*ListWeeklyXPRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{10}
}

func (x *ListWeeklyXPRequest) GetWeeks() int32 {
	if x != nil {
		return x.Weeks
	}
	return 0
}

type WeeklyXPItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeekLabel     string                 `protobuf:"bytes,1,opt,name=week_label,json=weekLabel,proto3" json:"week_label,omitempty"`
	Xp            int32                  `protobuf:"varint,2,opt,name=xp,proto3" json:"xp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeeklyXPItem) Reset() {
	*x = WeeklyXPItem{}
	mi := &file_profile_v1_profile_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeeklyXPItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeeklyXPItem) ProtoMessage() {}

func (x *WeeklyXPItem) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeeklyXPItem.ProtoReflect.Descriptor instead.
func (*WeeklyXPItem) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{11}
}

func (x *WeeklyXPItem) GetWeekLabel() string {
	if x != nil {
		return x.WeekLabel
	}
	return ""
}

func (x *WeeklyXPItem) GetXp() int32 {
	if x != nil {
		return x.Xp
	}
	return 0
}

type WeeklyXPList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*WeeklyXPItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeeklyXPList) Reset() {
	*x = WeeklyXPList{}
	mi := &file_profile_v1_profile_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeeklyXPList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeeklyXPList) ProtoMessage() {}

func (x *WeeklyXPList) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeeklyXPList.ProtoReflect.Descriptor instead.
func (*WeeklyXPList) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{12}
}

func (x *WeeklyXPList) GetItems() []*WeeklyXPItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CompleteOnboardingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	AgeRange      string                 `protobuf:"bytes,3,opt,name=age_range,json=ageRange,proto3" json:"age_range,omitempty"`
	HowHeard      string                 `protobuf:"bytes,4,opt,name=how_heard,json=howHeard,proto3" json:"how_heard,omitempty"`
	WhyLearn      string                 `protobuf:"bytes,5,opt,name=why_learn,json=whyLearn,proto3" json:"why_learn,omitempty"`
	Level         string                 `protobuf:"bytes,6,opt,name=level,proto3" json:"level,omitempty"`
	Username      string                 `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"` // optional; FE may send editable prefilled username
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOnboardingRequest) Reset() {
	*x = CompleteOnboardingRequest{}
	mi := &file_profile_v1_profile_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOnboardingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOnboardingRequest) ProtoMessage() {}

func (x *CompleteOnboardingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOnboardingRequest.ProtoReflect.Descriptor instead.
func (*CompleteOnboardingRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{13}
}

func (x *CompleteOnboardingRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetAgeRange() string {
	if x != nil {
		return x.AgeRange
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetHowHeard() string {
	if x != nil {
		return x.HowHeard
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetWhyLearn() string {
	if x != nil {
		return x.WhyLearn
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type LinkedAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	LinkedAt      string                 `protobuf:"bytes,3,opt,name=linked_at,json=linkedAt,proto3" json:"linked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkedAccount) Reset() {
	*x = LinkedAccount{}
	mi := &file_profile_v1_profile_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkedAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkedAccount) ProtoMessage() {}

func (x *LinkedAccount) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkedAccount.ProtoReflect.Descriptor instead.
func (*LinkedAccount) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{14}
}

func (x *LinkedAccount) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LinkedAccount) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LinkedAccount) GetLinkedAt() string {
	if x != nil {
		return x.LinkedAt
	}
	return ""
}

type LinkedAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*LinkedAccount       `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkedAccountsResponse) Reset() {
	*x = LinkedAccountsResponse{}
	mi := &file_profile_v1_profile_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkedAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkedAccountsResponse) ProtoMessage() {}

func (x *LinkedAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkedAccountsResponse.ProtoReflect.Descriptor instead.
func (*LinkedAccountsResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{15}
}

func (x *LinkedAccountsResponse) GetAccounts() []*LinkedAccount {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type UserSettings struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SoundEffects         bool                   `protobuf:"varint,1,opt,name=sound_effects,json=soundEffects,proto3" json:"sound_effects,omitempty"`
	Animations           bool                   `protobuf:"varint,2,opt,name=animations,proto3" json:"animations,omitempty"`
	MotivationalMessages bool                   `protobuf:"varint,3,opt,name=motivational_messages,json=motivationalMessages,proto3" json:"motivational_messages,omitempty"`
	ListeningExercises   bool                   `protobuf:"varint,4,opt,name=listening_exercises,json=listeningExercises,proto3" json:"listening_exercises,omitempty"`
	Theme                string                 `protobuf:"bytes,5,opt,name=theme,proto3" json:"theme,omitempty"`
	Locale               string                 `protobuf:"bytes,6,opt,name=locale,proto3" json:"locale,omitempty"`
	PrivacyJson          string                 `protobuf:"bytes,7,opt,name=privacy_json,json=privacyJson,proto3" json:"privacy_json,omitempty"` // JSON string
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UserSettings) Reset() {
	*x = UserSettings{}
	mi := &file_profile_v1_profile_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSettings) ProtoMessage() {}

func (x *UserSettings) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSettings.ProtoReflect.Descriptor instead.
func (*UserSettings) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{16}
}

func (x *UserSettings) GetSoundEffects() bool {
	if x != nil {
		return x.SoundEffects
	}
	return false
}

func (x *UserSettings) GetAnimations() bool {
	if x != nil {
		return x.Animations
	}
	return false
}

func (x *UserSettings) GetMotivationalMessages() bool {
	if x != nil {
		return x.MotivationalMessages
	}
	return false
}

func (x *UserSettings) GetListeningExercises() bool {
	if x != nil {
		return x.ListeningExercises
	}
	return false
}

func (x *UserSettings) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *UserSettings) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *UserSettings) GetPrivacyJson() string {
	if x != nil {
		return x.PrivacyJson
	}
	return ""
}

type UpdateSettingsRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SoundEffects         *bool                  `protobuf:"varint,1,opt,name=sound_effects,json=soundEffects,proto3,oneof" json:"sound_effects,omitempty"`
	Animations           *bool                  `protobuf:"varint,2,opt,name=animations,proto3,oneof" json:"animations,omitempty"`
	MotivationalMessages *bool                  `protobuf:"varint,3,opt,name=motivational_messages,json=motivationalMessages,proto3,oneof" json:"motivational_messages,omitempty"`
	ListeningExercises   *bool                  `protobuf:"varint,4,opt,name=listening_exercises,json=listeningExercises,proto3,oneof" json:"listening_exercises,omitempty"`
	Theme                *string                `protobuf:"bytes,5,opt,name=theme,proto3,oneof" json:"theme,omitempty"`
	Locale               *string                `protobuf:"bytes,6,opt,name=locale,proto3,oneof" json:"locale,omitempty"`
	PrivacyJson          *string                `protobuf:"bytes,7,opt,name=privacy_json,json=privacyJson,proto3,oneof" json:"privacy_json,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateSettingsRequest) Reset() {
	*x = UpdateSettingsRequest{}
	mi := &file_profile_v1_profile_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingsRequest) ProtoMessage() {}

func (x *UpdateSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateSettingsRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateSettingsRequest) GetSoundEffects() bool {
	if x != nil && x.SoundEffects != nil {
		return *x.SoundEffects
	}
	return false
}

func (x *UpdateSettingsRequest) GetAnimations() bool {
	if x != nil && x.Animations != nil {
		return *x.Animations
	}
	return false
}

func (x *UpdateSettingsRequest) GetMotivationalMessages() bool {
	if x != nil && x.MotivationalMessages != nil {
		return *x.MotivationalMessages
	}
	return false
}

func (x *UpdateSettingsRequest) GetListeningExercises() bool {
	if x != nil && x.ListeningExercises != nil {
		return *x.ListeningExercises
	}
	return false
}

func (x *UpdateSettingsRequest) GetTheme() string {
	if x != nil && x.Theme != nil {
		return *x.Theme
	}
	return ""
}

func (x *UpdateSettingsRequest) GetLocale() string {
	if x != nil && x.Locale != nil {
		return *x.Locale
	}
	return ""
}

func (x *UpdateSettingsRequest) GetPrivacyJson() string {
	if x != nil && x.PrivacyJson != nil {
		return *x.PrivacyJson
	}
	return ""
}

type MergeSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guest         *UserSettings          `protobuf:"bytes,1,opt,name=guest,proto3" json:"guest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeSettingsRequest) Reset() {
	*x = MergeSettingsRequest{}
	mi := &file_profile_v1_profile_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeSettingsRequest) ProtoMessage() {}

func (x *MergeSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeSettingsRequest.ProtoReflect.Descriptor instead.
func (*MergeSettingsRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{18}
}

func (x *MergeSettingsRequest) GetGuest() *UserSettings {
	if x != nil {
		return x.Guest
	}
	return nil
}

type MergeSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *UserSettings          `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	FieldsMerged  []string               `protobuf:"bytes,2,rep,name=fields_merged,json=fieldsMerged,proto3" json:"fields_merged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeSettingsResponse) Reset() {
	*x = MergeSettingsResponse{}
	mi := &file_profile_v1_profile_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeSettingsResponse) ProtoMessage() {}

func (x *MergeSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeSettingsResponse.ProtoReflect.Descriptor instead.
func (*MergeSettingsResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{19}
}

func (x *MergeSettingsResponse) GetSettings() *UserSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *MergeSettingsResponse) GetFieldsMerged() []string {
	if x != nil {
		return x.FieldsMerged
	}
	return nil
}

var File_profile_v1_profile_proto protoreflect.FileDescriptor

const file_profile_v1_profile_proto_rawDesc = "" +
	"\n" +
	"\x18profile/v1/profile.proto\x12\x15puchi.core.profile.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x9b\x02\n" +
	"\vAchievement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\x12\x1a\n" +
	"\bprogress\x18\x06 \x01(\x05R\bprogress\x12%\n" +
	"\x0eprogress_label\x18\a \x01(\tR\rprogressLabel\x12\x1a\n" +
	"\bunlocked\x18\b \x01(\bR\bunlocked\x12;\n" +
	"\vunlocked_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"unlockedAt\"K\n" +
	"\x0fAchievementList\x128\n" +
	"\x05items\x18\x01 \x03(\v2\".puchi.core.profile.v1.AchievementR\x05items\"\xca\x03\n" +
	"\x05Stats\x12#\n" +
	"\rtotal_lessons\x18\x01 \x01(\x05R\ftotalLessons\x12+\n" +
	"\x11completed_lessons\x18\x02 \x01(\x05R\x10completedLessons\x12#\n" +
	"\rtotal_minutes\x18\x03 \x01(\x05R\ftotalMinutes\x12\x1a\n" +
	"\baccuracy\x18\x04 \x01(\x02R\baccuracy\x12#\n" +
	"\rwords_learned\x18\x05 \x01(\x05R\fwordsLearned\x12\x1d\n" +
	"\n" +
	"current_xp\x18\x06 \x01(\x05R\tcurrentXp\x12\x19\n" +
	"\btotal_xp\x18\a \x01(\x05R\atotalXp\x12\x14\n" +
	"\x05level\x18\b \x01(\x05R\x05level\x12'\n" +
	"\x10xp_to_next_level\x18\t \x01(\x05R\rxpToNextLevel\x12\x16\n" +
	"\x06streak\x18\n" +
	" \x01(\x05R\x06streak\x12%\n" +
	"\x0elongest_streak\x18\v \x01(\x05R\rlongestStreak\x12%\n" +
	"\x0estreak_freezes\x18\f \x01(\x05R\rstreakFreezes\x12\x16\n" +
	"\x06crowns\x18\r \x01(\x05R\x06crowns\x12\x12\n" +
	"\x04gems\x18\x0e \x01(\x05R\x04gems\"\xfb\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x06 \x01(\tR\tavatarUrl\x12\x10\n" +
	"\x03bio\x18\a \x01(\tR\x03bio\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x121\n" +
	"\x14onboarding_completed\x18\n" +
	" \x01(\bR\x13onboardingCompleted\x12\x1b\n" +
	"\tage_range\x18\v \x01(\tR\bageRange\"\x9d\x01\n" +
	"\x14UpdateProfileRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\x12\x1b\n" +
	"\tage_range\x18\x05 \x01(\tR\bageRange\"4\n" +
	"\x13UpdateAvatarRequest\x12\x1d\n" +
	"\n" +
	"avatar_key\x18\x01 \x01(\tR\tavatarKey\"9\n" +
	"\x1bGetProfileByUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\">\n" +
	"\x18ListDailyActivityRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"\x96\x01\n" +
	"\x11DailyActivityItem\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12+\n" +
	"\x11lessons_completed\x18\x02 \x01(\x05R\x10lessonsCompleted\x12\x1b\n" +
	"\txp_earned\x18\x03 \x01(\x05R\bxpEarned\x12#\n" +
	"\rminutes_spent\x18\x04 \x01(\x05R\fminutesSpent\"S\n" +
	"\x11DailyActivityList\x12>\n" +
	"\x05items\x18\x01 \x03(\v2(.puchi.core.profile.v1.DailyActivityItemR\x05items\"+\n" +
	"\x13ListWeeklyXPRequest\x12\x14\n" +
	"\x05weeks\x18\x01 \x01(\x05R\x05weeks\"=\n" +
	"\fWeeklyXPItem\x12\x1d\n" +
	"\n" +
	"week_label\x18\x01 \x01(\tR\tweekLabel\x12\x0e\n" +
	"\x02xp\x18\x02 \x01(\x05R\x02xp\"I\n" +
	"\fWeeklyXPList\x129\n" +
	"\x05items\x18\x01 \x03(\v2#.puchi.core.profile.v1.WeeklyXPItemR\x05items\"\xe0\x01\n" +
	"\x19CompleteOnboardingRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x1b\n" +
	"\tage_range\x18\x03 \x01(\tR\bageRange\x12\x1b\n" +
	"\thow_heard\x18\x04 \x01(\tR\bhowHeard\x12\x1b\n" +
	"\twhy_learn\x18\x05 \x01(\tR\bwhyLearn\x12\x14\n" +
	"\x05level\x18\x06 \x01(\tR\x05level\x12\x1a\n" +
	"\busername\x18\a \x01(\tR\busername\"^\n" +
	"\rLinkedAccount\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\tlinked_at\x18\x03 \x01(\tR\blinkedAt\"Z\n" +
	"\x16LinkedAccountsResponse\x12@\n" +
	"\baccounts\x18\x01 \x03(\v2$.puchi.core.profile.v1.LinkedAccountR\baccounts\"\x8a\x02\n" +
	"\fUserSettings\x12#\n" +
	"\rsound_effects\x18\x01 \x01(\bR\fsoundEffects\x12\x1e\n" +
	"\n" +
	"animations\x18\x02 \x01(\bR\n" +
	"animations\x123\n" +
	"\x15motivational_messages\x18\x03 \x01(\bR\x14motivationalMessages\x12/\n" +
	"\x13listening_exercises\x18\x04 \x01(\bR\x12listeningExercises\x12\x14\n" +
	"\x05theme\x18\x05 \x01(\tR\x05theme\x12\x16\n" +
	"\x06locale\x18\x06 \x01(\tR\x06locale\x12!\n" +
	"\fprivacy_json\x18\a \x01(\tR\vprivacyJson\"\xaf\x03\n" +
	"\x15UpdateSettingsRequest\x12(\n" +
	"\rsound_effects\x18\x01 \x01(\bH\x00R\fsoundEffects\x88\x01\x01\x12#\n" +
	"\n" +
	"animations\x18\x02 \x01(\bH\x01R\n" +
	"animations\x88\x01\x01\x128\n" +
	"\x15motivational_messages\x18\x03 \x01(\bH\x02R\x14motivationalMessages\x88\x01\x01\x124\n" +
	"\x13listening_exercises\x18\x04 \x01(\bH\x03R\x12listeningExercises\x88\x01\x01\x12\x19\n" +
	"\x05theme\x18\x05 \x01(\tH\x04R\x05theme\x88\x01\x01\x12\x1b\n" +
	"\x06locale\x18\x06 \x01(\tH\x05R\x06locale\x88\x01\x01\x12&\n" +
	"\fprivacy_json\x18\a \x01(\tH\x06R\vprivacyJson\x88\x01\x01B\x10\n" +
	"\x0e_sound_effectsB\r\n" +
	"\v_animationsB\x18\n" +
	"\x16_motivational_messagesB\x16\n" +
	"\x14_listening_exercisesB\b\n" +
	"\x06_themeB\t\n" +
	"\a_localeB\x0f\n" +
	"\r_privacy_json\"Q\n" +
	"\x14MergeSettingsRequest\x129\n" +
	"\x05guest\x18\x01 \x01(\v2#.puchi.core.profile.v1.UserSettingsR\x05guest\"}\n" +
	"\x15MergeSettingsResponse\x12?\n" +
	"\bsettings\x18\x01 \x01(\v2#.puchi.core.profile.v1.UserSettingsR\bsettings\x12#\n" +
	"\rfields_merged\x18\x02 \x03(\tR\ffieldsMerged2\xe2\f\n" +
	"\x0eProfileService\x12V\n" +
	"\n" +
	"GetProfile\x12\x16.google.protobuf.Empty\x1a\x1b.puchi.core.profile.v1.User\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/profile\x12q\n" +
	"\rUpdateProfile\x12+.puchi.core.profile.v1.UpdateProfileRequest\x1a\x1b.puchi.core.profile.v1.User\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\x1a\v/v1/profile\x12[\n" +
	"\bGetStats\x12\x16.google.protobuf.Empty\x1a\x1c.puchi.core.profile.v1.Stats\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/profile/stats\x12\x98\x01\n" +
	"\x11ListDailyActivity\x12/.puchi.core.profile.v1.ListDailyActivityRequest\x1a(.puchi.core.profile.v1.DailyActivityList\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/profile/stats/daily-activity\x12\x84\x01\n" +
	"\fListWeeklyXP\x12*.puchi.core.profile.v1.ListWeeklyXPRequest\x1a#.puchi.core.profile.v1.WeeklyXPList\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/profile/stats/weekly-xp\x12t\n" +
	"\x10ListAchievements\x12\x16.google.protobuf.Empty\x1a&.puchi.core.profile.v1.AchievementList\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/profile/achievements\x12\x87\x01\n" +
	"\x14GetProfileByUsername\x122.puchi.core.profile.v1.GetProfileByUsernameRequest\x1a\x1b.puchi.core.profile.v1.User\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/profile/{username}\x12v\n" +
	"\fUpdateAvatar\x12*.puchi.core.profile.v1.UpdateAvatarRequest\x1a\x1b.puchi.core.profile.v1.User\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/v1/profile/avatar\x12\x87\x01\n" +
	"\x12CompleteOnboarding\x120.puchi.core.profile.v1.CompleteOnboardingRequest\x1a\x1b.puchi.core.profile.v1.User\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/onboarding/complete\x12\x7f\n" +
	"\x11GetLinkedAccounts\x12\x16.google.protobuf.Empty\x1a-.puchi.core.profile.v1.LinkedAccountsResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/profile/linked-accounts\x12h\n" +
	"\vGetSettings\x12\x16.google.protobuf.Empty\x1a#.puchi.core.profile.v1.UserSettings\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/profile/settings\x12\x84\x01\n" +
	"\x0eUpdateSettings\x12,.puchi.core.profile.v1.UpdateSettingsRequest\x1a#.puchi.core.profile.v1.UserSettings\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*2\x14/v1/profile/settings\x12\x91\x01\n" +
	"\rMergeSettings\x12+.puchi.core.profile.v1.MergeSettingsRequest\x1a,.puchi.core.profile.v1.MergeSettingsResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/profile/settings/mergeBl\n" +
	"\x1bio.grpc.examples.profile.v1B\fProfileProtoP\x01Z=github.com/puchidemy/puchi-backend/app/core/api/profile/v1;v1b\x06proto3"

var (
	file_profile_v1_profile_proto_rawDescOnce sync.Once
	file_profile_v1_profile_proto_rawDescData []byte
)

func file_profile_v1_profile_proto_rawDescGZIP() []byte {
	file_profile_v1_profile_proto_rawDescOnce.Do(func() {
		file_profile_v1_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_v1_profile_proto_rawDesc), len(file_profile_v1_profile_proto_rawDesc)))
	})
	return file_profile_v1_profile_proto_rawDescData
}

var file_profile_v1_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_profile_v1_profile_proto_goTypes = []any{
	(*Achievement)(nil),                 // 0: puchi.core.profile.v1.Achievement
	(*AchievementList)(nil),             // 1: puchi.core.profile.v1.AchievementList
	(*Stats)(nil),                       // 2: puchi.core.profile.v1.Stats
	(*User)(nil),                        // 3: puchi.core.profile.v1.User
	(*UpdateProfileRequest)(nil),        // 4: puchi.core.profile.v1.UpdateProfileRequest
	(*UpdateAvatarRequest)(nil),         // 5: puchi.core.profile.v1.UpdateAvatarRequest
	(*GetProfileByUsernameRequest)(nil), // 6: puchi.core.profile.v1.GetProfileByUsernameRequest
	(*ListDailyActivityRequest)(nil),    // 7: puchi.core.profile.v1.ListDailyActivityRequest
	(*DailyActivityItem)(nil),           // 8: puchi.core.profile.v1.DailyActivityItem
	(*DailyActivityList)(nil),           // 9: puchi.core.profile.v1.DailyActivityList
	(*ListWeeklyXPRequest)(nil),         // 10: puchi.core.profile.v1.ListWeeklyXPRequest
	(*WeeklyXPItem)(nil),                // 11: puchi.core.profile.v1.WeeklyXPItem
	(*WeeklyXPList)(nil),                // 12: puchi.core.profile.v1.WeeklyXPList
	(*CompleteOnboardingRequest)(nil),   // 13: puchi.core.profile.v1.CompleteOnboardingRequest
	(*LinkedAccount)(nil),               // 14: puchi.core.profile.v1.LinkedAccount
	(*LinkedAccountsResponse)(nil),      // 15: puchi.core.profile.v1.LinkedAccountsResponse
	(*UserSettings)(nil),                // 16: puchi.core.profile.v1.UserSettings
	(*UpdateSettingsRequest)(nil),       // 17: puchi.core.profile.v1.UpdateSettingsRequest
	(*MergeSettingsRequest)(nil),        // 18: puchi.core.profile.v1.MergeSettingsRequest
	(*MergeSettingsResponse)(nil),       // 19: puchi.core.profile.v1.MergeSettingsResponse
	(*timestamppb.Timestamp)(nil),       // 20: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 21: google.protobuf.Empty
}
var file_profile_v1_profile_proto_depIdxs = []int32{
	20, // 0: puchi.core.profile.v1.Achievement.unlocked_at:type_name -> google.protobuf.Timestamp
	0,  // 1: puchi.core.profile.v1.AchievementList.items:type_name -> puchi.core.profile.v1.Achievement
	20, // 2: puchi.core.profile.v1.User.created_at:type_name -> google.protobuf.Timestamp
	20, // 3: puchi.core.profile.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 4: puchi.core.profile.v1.DailyActivityList.items:type_name -> puchi.core.profile.v1.DailyActivityItem
	11, // 5: puchi.core.profile.v1.WeeklyXPList.items:type_name -> puchi.core.profile.v1.WeeklyXPItem
	14, // 6: puchi.core.profile.v1.LinkedAccountsResponse.accounts:type_name -> puchi.core.profile.v1.LinkedAccount
	16, // 7: puchi.core.profile.v1.MergeSettingsRequest.guest:type_name -> puchi.core.profile.v1.UserSettings
	16, // 8: puchi.core.profile.v1.MergeSettingsResponse.settings:type_name -> puchi.core.profile.v1.UserSettings
	21, // 9: puchi.core.profile.v1.ProfileService.GetProfile:input_type -> google.protobuf.Empty
	4,  // 10: puchi.core.profile.v1.ProfileService.UpdateProfile:input_type -> puchi.core.profile.v1.UpdateProfileRequest
	21, // 11: puchi.core.profile.v1.ProfileService.GetStats:input_type -> google.protobuf.Empty
	7,  // 12: puchi.core.profile.v1.ProfileService.ListDailyActivity:input_type -> puchi.core.profile.v1.ListDailyActivityRequest
	10, // 13: puchi.core.profile.v1.ProfileService.ListWeeklyXP:input_type -> puchi.core.profile.v1.ListWeeklyXPRequest
	21, // 14: puchi.core.profile.v1.ProfileService.ListAchievements:input_type -> google.protobuf.Empty
	6,  // 15: puchi.core.profile.v1.ProfileService.GetProfileByUsername:input_type -> puchi.core.profile.v1.GetProfileByUsernameRequest
	5,  // 16: puchi.core.profile.v1.ProfileService.UpdateAvatar:input_type -> puchi.core.profile.v1.UpdateAvatarRequest
	13, // 17: puchi.core.profile.v1.ProfileService.CompleteOnboarding:input_type -> puchi.core.profile.v1.CompleteOnboardingRequest
	21, // 18: puchi.core.profile.v1.ProfileService.GetLinkedAccounts:input_type -> google.protobuf.Empty
	21, // 19: puchi.core.profile.v1.ProfileService.GetSettings:input_type -> google.protobuf.Empty
	17, // 20: puchi.core.profile.v1.ProfileService.UpdateSettings:input_type -> puchi.core.profile.v1.UpdateSettingsRequest
	18, // 21: puchi.core.profile.v1.ProfileService.MergeSettings:input_type -> puchi.core.profile.v1.MergeSettingsRequest
	3,  // 22: puchi.core.profile.v1.ProfileService.GetProfile:output_type -> puchi.core.profile.v1.User
	3,  // 23: puchi.core.profile.v1.ProfileService.UpdateProfile:output_type -> puchi.core.profile.v1.User
	2,  // 24: puchi.core.profile.v1.ProfileService.GetStats:output_type -> puchi.core.profile.v1.Stats
	9,  // 25: puchi.core.profile.v1.ProfileService.ListDailyActivity:output_type -> puchi.core.profile.v1.DailyActivityList
	12, // 26: puchi.core.profile.v1.ProfileService.ListWeeklyXP:output_type -> puchi.core.profile.v1.WeeklyXPList
	1,  // 27: puchi.core.profile.v1.ProfileService.ListAchievements:output_type -> puchi.core.profile.v1.AchievementList
	3,  // 28: puchi.core.profile.v1.ProfileService.GetProfileByUsername:output_type -> puchi.core.profile.v1.User
	3,  // 29: puchi.core.profile.v1.ProfileService.UpdateAvatar:output_type -> puchi.core.profile.v1.User
	3,  // 30: puchi.core.profile.v1.ProfileService.CompleteOnboarding:output_type -> puchi.core.profile.v1.User
	15, // 31: puchi.core.profile.v1.ProfileService.GetLinkedAccounts:output_type -> puchi.core.profile.v1.LinkedAccountsResponse
	16, // 32: puchi.core.profile.v1.ProfileService.GetSettings:output_type -> puchi.core.profile.v1.UserSettings
	16, // 33: puchi.core.profile.v1.ProfileService.UpdateSettings:output_type -> puchi.core.profile.v1.UserSettings
	19, // 34: puchi.core.profile.v1.ProfileService.MergeSettings:output_type -> puchi.core.profile.v1.MergeSettingsResponse
	22, // [22:35] is the sub-list for method output_type
	9,  // [9:22] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_profile_v1_profile_proto_init() }
func file_profile_v1_profile_proto_init() {
	if File_profile_v1_profile_proto != nil {
		return
	}
	file_profile_v1_profile_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_v1_profile_proto_rawDesc), len(file_profile_v1_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_v1_profile_proto_goTypes,
		DependencyIndexes: file_profile_v1_profile_proto_depIdxs,
		MessageInfos:      file_profile_v1_profile_proto_msgTypes,
	}.Build()
	File_profile_v1_profile_proto = out.File
	file_profile_v1_profile_proto_goTypes = nil
	file_profile_v1_profile_proto_depIdxs = nil
}
