// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: profile/v1/profile.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationProfileServiceCompleteOnboarding = "/puchi.core.profile.v1.ProfileService/CompleteOnboarding"
const OperationProfileServiceGetLinkedAccounts = "/puchi.core.profile.v1.ProfileService/GetLinkedAccounts"
const OperationProfileServiceGetProfile = "/puchi.core.profile.v1.ProfileService/GetProfile"
const OperationProfileServiceGetProfileByUsername = "/puchi.core.profile.v1.ProfileService/GetProfileByUsername"
const OperationProfileServiceGetStats = "/puchi.core.profile.v1.ProfileService/GetStats"
const OperationProfileServiceListAchievements = "/puchi.core.profile.v1.ProfileService/ListAchievements"
const OperationProfileServiceUpdateProfile = "/puchi.core.profile.v1.ProfileService/UpdateProfile"

type ProfileServiceHTTPServer interface {
	CompleteOnboarding(context.Context, *CompleteOnboardingRequest) (*User, error)
	GetLinkedAccounts(context.Context, *emptypb.Empty) (*LinkedAccountsResponse, error)
	GetProfile(context.Context, *emptypb.Empty) (*User, error)
	GetProfileByUsername(context.Context, *GetProfileByUsernameRequest) (*User, error)
	GetStats(context.Context, *emptypb.Empty) (*Stats, error)
	ListAchievements(context.Context, *emptypb.Empty) (*AchievementList, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*User, error)
}

func RegisterProfileServiceHTTPServer(s *http.Server, srv ProfileServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/profile", _ProfileService_GetProfile0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/profile", _ProfileService_UpdateProfile0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/profile/stats", _ProfileService_GetStats0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/profile/achievements", _ProfileService_ListAchievements0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/profile/{username}", _ProfileService_GetProfileByUsername0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/onboarding/complete", _ProfileService_CompleteOnboarding0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/profile/linked-accounts", _ProfileService_GetLinkedAccounts0_HTTP_Handler(srv))
}

func _ProfileService_GetProfile0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceGetProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProfile(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*User)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_UpdateProfile0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceUpdateProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProfile(ctx, req.(*UpdateProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*User)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_GetStats0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceGetStats)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetStats(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Stats)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_ListAchievements0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceListAchievements)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAchievements(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AchievementList)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_GetProfileByUsername0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProfileByUsernameRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceGetProfileByUsername)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProfileByUsername(ctx, req.(*GetProfileByUsernameRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*User)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_CompleteOnboarding0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CompleteOnboardingRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceCompleteOnboarding)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CompleteOnboarding(ctx, req.(*CompleteOnboardingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*User)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_GetLinkedAccounts0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceGetLinkedAccounts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLinkedAccounts(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LinkedAccountsResponse)
		return ctx.Result(200, reply)
	}
}

type ProfileServiceHTTPClient interface {
	CompleteOnboarding(ctx context.Context, req *CompleteOnboardingRequest, opts ...http.CallOption) (rsp *User, err error)
	GetLinkedAccounts(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *LinkedAccountsResponse, err error)
	GetProfile(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *User, err error)
	GetProfileByUsername(ctx context.Context, req *GetProfileByUsernameRequest, opts ...http.CallOption) (rsp *User, err error)
	GetStats(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *Stats, err error)
	ListAchievements(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *AchievementList, err error)
	UpdateProfile(ctx context.Context, req *UpdateProfileRequest, opts ...http.CallOption) (rsp *User, err error)
}

type ProfileServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewProfileServiceHTTPClient(client *http.Client) ProfileServiceHTTPClient {
	return &ProfileServiceHTTPClientImpl{client}
}

func (c *ProfileServiceHTTPClientImpl) CompleteOnboarding(ctx context.Context, in *CompleteOnboardingRequest, opts ...http.CallOption) (*User, error) {
	var out User
	pattern := "/v1/onboarding/complete"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProfileServiceCompleteOnboarding),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) GetLinkedAccounts(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*LinkedAccountsResponse, error) {
	var out LinkedAccountsResponse
	pattern := "/v1/profile/linked-accounts"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationProfileServiceGetLinkedAccounts),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) GetProfile(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*User, error) {
	var out User
	pattern := "/v1/profile"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationProfileServiceGetProfile),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) GetProfileByUsername(ctx context.Context, in *GetProfileByUsernameRequest, opts ...http.CallOption) (*User, error) {
	var out User
	pattern := "/v1/profile/{username}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationProfileServiceGetProfileByUsername),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) GetStats(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*Stats, error) {
	var out Stats
	pattern := "/v1/profile/stats"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationProfileServiceGetStats),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) ListAchievements(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*AchievementList, error) {
	var out AchievementList
	pattern := "/v1/profile/achievements"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationProfileServiceListAchievements),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...http.CallOption) (*User, error) {
	var out User
	pattern := "/v1/profile"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProfileServiceUpdateProfile),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
