// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: media/v1/media.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestUploadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`                                 // "avatar", "lesson_image", "lesson_audio", "recording"
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`        // "image/webp", "audio/mpeg"
	ContentLength int64                  `protobuf:"varint,3,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"` // for validation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestUploadURLRequest) Reset() {
	*x = RequestUploadURLRequest{}
	mi := &file_media_v1_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUploadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUploadURLRequest) ProtoMessage() {}

func (x *RequestUploadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUploadURLRequest.ProtoReflect.Descriptor instead.
func (*RequestUploadURLRequest) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{0}
}

func (x *RequestUploadURLRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *RequestUploadURLRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *RequestUploadURLRequest) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

type RequestUploadURLResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UploadUrl        string                 `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	ObjectKey        string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	MediaId          int64                  `protobuf:"varint,3,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	ExpiresInSeconds int64                  `protobuf:"varint,4,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RequestUploadURLResponse) Reset() {
	*x = RequestUploadURLResponse{}
	mi := &file_media_v1_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUploadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUploadURLResponse) ProtoMessage() {}

func (x *RequestUploadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUploadURLResponse.ProtoReflect.Descriptor instead.
func (*RequestUploadURLResponse) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{1}
}

func (x *RequestUploadURLResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *RequestUploadURLResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *RequestUploadURLResponse) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *RequestUploadURLResponse) GetExpiresInSeconds() int64 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

type FinalizeUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int64                  `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeUploadRequest) Reset() {
	*x = FinalizeUploadRequest{}
	mi := &file_media_v1_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeUploadRequest) ProtoMessage() {}

func (x *FinalizeUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeUploadRequest.ProtoReflect.Descriptor instead.
func (*FinalizeUploadRequest) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{2}
}

func (x *FinalizeUploadRequest) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

type MediaObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"` // CDN or presigned GET URL
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Width         int32                  `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	DurationMs    int32                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Category      string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	ContentType   string                 `protobuf:"bytes,8,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaObject) Reset() {
	*x = MediaObject{}
	mi := &file_media_v1_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaObject) ProtoMessage() {}

func (x *MediaObject) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaObject.ProtoReflect.Descriptor instead.
func (*MediaObject) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{3}
}

func (x *MediaObject) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MediaObject) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MediaObject) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *MediaObject) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MediaObject) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MediaObject) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *MediaObject) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MediaObject) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type GetMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaRequest) Reset() {
	*x = GetMediaRequest{}
	mi := &file_media_v1_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaRequest) ProtoMessage() {}

func (x *GetMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaRequest.ProtoReflect.Descriptor instead.
func (*GetMediaRequest) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{4}
}

func (x *GetMediaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaRequest) Reset() {
	*x = DeleteMediaRequest{}
	mi := &file_media_v1_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaRequest) ProtoMessage() {}

func (x *DeleteMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaRequest.ProtoReflect.Descriptor instead.
func (*DeleteMediaRequest) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteMediaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_media_v1_media_proto protoreflect.FileDescriptor

const file_media_v1_media_proto_rawDesc = "" +
	"\n" +
	"\x14media/v1/media.proto\x12\x0epuchi.media.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x7f\n" +
	"\x17RequestUploadURLRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12%\n" +
	"\x0econtent_length\x18\x03 \x01(\x03R\rcontentLength\"\xa1\x01\n" +
	"\x18RequestUploadURLResponse\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x01 \x01(\tR\tuploadUrl\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\x12\x19\n" +
	"\bmedia_id\x18\x03 \x01(\x03R\amediaId\x12,\n" +
	"\x12expires_in_seconds\x18\x04 \x01(\x03R\x10expiresInSeconds\"2\n" +
	"\x15FinalizeUploadRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x03R\amediaId\"\xdc\x01\n" +
	"\vMediaObject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x05R\x06height\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x05R\n" +
	"durationMs\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12!\n" +
	"\fcontent_type\x18\b \x01(\tR\vcontentType\"!\n" +
	"\x0fGetMediaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"$\n" +
	"\x12DeleteMediaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\xa1\x03\n" +
	"\fMediaService\x12\x86\x01\n" +
	"\x10RequestUploadURL\x12'.puchi.media.v1.RequestUploadURLRequest\x1a(.puchi.media.v1.RequestUploadURLResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/media/upload-url\x12s\n" +
	"\x0eFinalizeUpload\x12%.puchi.media.v1.FinalizeUploadRequest\x1a\x1b.puchi.media.v1.MediaObject\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/media/finalize\x12H\n" +
	"\bGetMedia\x12\x1f.puchi.media.v1.GetMediaRequest\x1a\x1b.puchi.media.v1.MediaObject\x12I\n" +
	"\vDeleteMedia\x12\".puchi.media.v1.DeleteMediaRequest\x1a\x16.google.protobuf.EmptyBg\n" +
	"\x19io.grpc.examples.media.v1B\n" +
	"MediaProtoP\x01Z<github.com/puchidemy/puchi-backend/app/media/api/media/v1;v1b\x06proto3"

var (
	file_media_v1_media_proto_rawDescOnce sync.Once
	file_media_v1_media_proto_rawDescData []byte
)

func file_media_v1_media_proto_rawDescGZIP() []byte {
	file_media_v1_media_proto_rawDescOnce.Do(func() {
		file_media_v1_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_v1_media_proto_rawDesc), len(file_media_v1_media_proto_rawDesc)))
	})
	return file_media_v1_media_proto_rawDescData
}

var file_media_v1_media_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_media_v1_media_proto_goTypes = []any{
	(*RequestUploadURLRequest)(nil),  // 0: puchi.media.v1.RequestUploadURLRequest
	(*RequestUploadURLResponse)(nil), // 1: puchi.media.v1.RequestUploadURLResponse
	(*FinalizeUploadRequest)(nil),    // 2: puchi.media.v1.FinalizeUploadRequest
	(*MediaObject)(nil),              // 3: puchi.media.v1.MediaObject
	(*GetMediaRequest)(nil),          // 4: puchi.media.v1.GetMediaRequest
	(*DeleteMediaRequest)(nil),       // 5: puchi.media.v1.DeleteMediaRequest
	(*emptypb.Empty)(nil),            // 6: google.protobuf.Empty
}
var file_media_v1_media_proto_depIdxs = []int32{
	0, // 0: puchi.media.v1.MediaService.RequestUploadURL:input_type -> puchi.media.v1.RequestUploadURLRequest
	2, // 1: puchi.media.v1.MediaService.FinalizeUpload:input_type -> puchi.media.v1.FinalizeUploadRequest
	4, // 2: puchi.media.v1.MediaService.GetMedia:input_type -> puchi.media.v1.GetMediaRequest
	5, // 3: puchi.media.v1.MediaService.DeleteMedia:input_type -> puchi.media.v1.DeleteMediaRequest
	1, // 4: puchi.media.v1.MediaService.RequestUploadURL:output_type -> puchi.media.v1.RequestUploadURLResponse
	3, // 5: puchi.media.v1.MediaService.FinalizeUpload:output_type -> puchi.media.v1.MediaObject
	3, // 6: puchi.media.v1.MediaService.GetMedia:output_type -> puchi.media.v1.MediaObject
	6, // 7: puchi.media.v1.MediaService.DeleteMedia:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_media_v1_media_proto_init() }
func file_media_v1_media_proto_init() {
	if File_media_v1_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_v1_media_proto_rawDesc), len(file_media_v1_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_v1_media_proto_goTypes,
		DependencyIndexes: file_media_v1_media_proto_depIdxs,
		MessageInfos:      file_media_v1_media_proto_msgTypes,
	}.Build()
	File_media_v1_media_proto = out.File
	file_media_v1_media_proto_goTypes = nil
	file_media_v1_media_proto_depIdxs = nil
}
