// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: learn/v1/learn.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationLearnServiceClaimGuest = "/puchi.learn.v1.LearnService/ClaimGuest"
const OperationLearnServiceCompleteLesson = "/puchi.learn.v1.LearnService/CompleteLesson"
const OperationLearnServiceCreateGuestSession = "/puchi.learn.v1.LearnService/CreateGuestSession"
const OperationLearnServiceGetLesson = "/puchi.learn.v1.LearnService/GetLesson"
const OperationLearnServiceGetUnit = "/puchi.learn.v1.LearnService/GetUnit"
const OperationLearnServicePing = "/puchi.learn.v1.LearnService/Ping"
const OperationLearnServiceStartLesson = "/puchi.learn.v1.LearnService/StartLesson"
const OperationLearnServiceSubmitAnswer = "/puchi.learn.v1.LearnService/SubmitAnswer"

type LearnServiceHTTPServer interface {
	ClaimGuest(context.Context, *ClaimGuestRequest) (*ClaimGuestResponse, error)
	CompleteLesson(context.Context, *CompleteLessonRequest) (*CompleteLessonResponse, error)
	CreateGuestSession(context.Context, *emptypb.Empty) (*GuestSession, error)
	GetLesson(context.Context, *GetLessonRequest) (*GetLessonResponse, error)
	GetUnit(context.Context, *GetUnitRequest) (*GetUnitResponse, error)
	Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	StartLesson(context.Context, *StartLessonRequest) (*StartLessonResponse, error)
	SubmitAnswer(context.Context, *SubmitAnswerRequest) (*SubmitAnswerResponse, error)
}

func RegisterLearnServiceHTTPServer(s *http.Server, srv LearnServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/learn/ping", _LearnService_Ping0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/learn/guest/session", _LearnService_CreateGuestSession0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/learn/guest/claim", _LearnService_ClaimGuest0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/learn/units/{id}", _LearnService_GetUnit0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/learn/lessons/{id}", _LearnService_GetLesson0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/learn/lessons/{id}/start", _LearnService_StartLesson0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/learn/attempts/{attempt_id}/answer", _LearnService_SubmitAnswer0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/learn/lessons/{id}/complete", _LearnService_CompleteLesson0_HTTP_Handler(srv))
}

func _LearnService_Ping0_HTTP_Handler(srv LearnServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLearnServicePing)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Ping(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _LearnService_CreateGuestSession0_HTTP_Handler(srv LearnServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLearnServiceCreateGuestSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateGuestSession(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GuestSession)
		return ctx.Result(200, reply)
	}
}

func _LearnService_ClaimGuest0_HTTP_Handler(srv LearnServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ClaimGuestRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLearnServiceClaimGuest)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ClaimGuest(ctx, req.(*ClaimGuestRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ClaimGuestResponse)
		return ctx.Result(200, reply)
	}
}

func _LearnService_GetUnit0_HTTP_Handler(srv LearnServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUnitRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLearnServiceGetUnit)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUnit(ctx, req.(*GetUnitRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUnitResponse)
		return ctx.Result(200, reply)
	}
}

func _LearnService_GetLesson0_HTTP_Handler(srv LearnServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLessonRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLearnServiceGetLesson)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLesson(ctx, req.(*GetLessonRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetLessonResponse)
		return ctx.Result(200, reply)
	}
}

func _LearnService_StartLesson0_HTTP_Handler(srv LearnServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StartLessonRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLearnServiceStartLesson)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StartLesson(ctx, req.(*StartLessonRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StartLessonResponse)
		return ctx.Result(200, reply)
	}
}

func _LearnService_SubmitAnswer0_HTTP_Handler(srv LearnServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SubmitAnswerRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLearnServiceSubmitAnswer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitAnswer(ctx, req.(*SubmitAnswerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SubmitAnswerResponse)
		return ctx.Result(200, reply)
	}
}

func _LearnService_CompleteLesson0_HTTP_Handler(srv LearnServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CompleteLessonRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLearnServiceCompleteLesson)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CompleteLesson(ctx, req.(*CompleteLessonRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CompleteLessonResponse)
		return ctx.Result(200, reply)
	}
}

type LearnServiceHTTPClient interface {
	ClaimGuest(ctx context.Context, req *ClaimGuestRequest, opts ...http.CallOption) (rsp *ClaimGuestResponse, err error)
	CompleteLesson(ctx context.Context, req *CompleteLessonRequest, opts ...http.CallOption) (rsp *CompleteLessonResponse, err error)
	CreateGuestSession(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *GuestSession, err error)
	GetLesson(ctx context.Context, req *GetLessonRequest, opts ...http.CallOption) (rsp *GetLessonResponse, err error)
	GetUnit(ctx context.Context, req *GetUnitRequest, opts ...http.CallOption) (rsp *GetUnitResponse, err error)
	Ping(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	StartLesson(ctx context.Context, req *StartLessonRequest, opts ...http.CallOption) (rsp *StartLessonResponse, err error)
	SubmitAnswer(ctx context.Context, req *SubmitAnswerRequest, opts ...http.CallOption) (rsp *SubmitAnswerResponse, err error)
}

type LearnServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewLearnServiceHTTPClient(client *http.Client) LearnServiceHTTPClient {
	return &LearnServiceHTTPClientImpl{client}
}

func (c *LearnServiceHTTPClientImpl) ClaimGuest(ctx context.Context, in *ClaimGuestRequest, opts ...http.CallOption) (*ClaimGuestResponse, error) {
	var out ClaimGuestResponse
	pattern := "/v1/learn/guest/claim"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationLearnServiceClaimGuest),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LearnServiceHTTPClientImpl) CompleteLesson(ctx context.Context, in *CompleteLessonRequest, opts ...http.CallOption) (*CompleteLessonResponse, error) {
	var out CompleteLessonResponse
	pattern := "/v1/learn/lessons/{id}/complete"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationLearnServiceCompleteLesson),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LearnServiceHTTPClientImpl) CreateGuestSession(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*GuestSession, error) {
	var out GuestSession
	pattern := "/v1/learn/guest/session"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationLearnServiceCreateGuestSession),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LearnServiceHTTPClientImpl) GetLesson(ctx context.Context, in *GetLessonRequest, opts ...http.CallOption) (*GetLessonResponse, error) {
	var out GetLessonResponse
	pattern := "/v1/learn/lessons/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationLearnServiceGetLesson),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LearnServiceHTTPClientImpl) GetUnit(ctx context.Context, in *GetUnitRequest, opts ...http.CallOption) (*GetUnitResponse, error) {
	var out GetUnitResponse
	pattern := "/v1/learn/units/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationLearnServiceGetUnit),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LearnServiceHTTPClientImpl) Ping(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/learn/ping"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationLearnServicePing),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LearnServiceHTTPClientImpl) StartLesson(ctx context.Context, in *StartLessonRequest, opts ...http.CallOption) (*StartLessonResponse, error) {
	var out StartLessonResponse
	pattern := "/v1/learn/lessons/{id}/start"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationLearnServiceStartLesson),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LearnServiceHTTPClientImpl) SubmitAnswer(ctx context.Context, in *SubmitAnswerRequest, opts ...http.CallOption) (*SubmitAnswerResponse, error) {
	var out SubmitAnswerResponse
	pattern := "/v1/learn/attempts/{attempt_id}/answer"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationLearnServiceSubmitAnswer),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
