// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: learn/v1/learn.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LearnService_Ping_FullMethodName = "/puchi.learn.v1.LearnService/Ping"
)

// LearnServiceClient is the client API for LearnService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LearnService is an empty scaffold. Curriculum and guest-progress RPCs are
// added in later tasks of the learn-service reorg.
type LearnServiceClient interface {
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type learnServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLearnServiceClient(cc grpc.ClientConnInterface) LearnServiceClient {
	return &learnServiceClient{cc}
}

func (c *learnServiceClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LearnService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LearnServiceServer is the server API for LearnService service.
// All implementations must embed UnimplementedLearnServiceServer
// for forward compatibility.
//
// LearnService is an empty scaffold. Curriculum and guest-progress RPCs are
// added in later tasks of the learn-service reorg.
type LearnServiceServer interface {
	Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedLearnServiceServer()
}

// UnimplementedLearnServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLearnServiceServer struct{}

func (UnimplementedLearnServiceServer) Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedLearnServiceServer) mustEmbedUnimplementedLearnServiceServer() {}
func (UnimplementedLearnServiceServer) testEmbeddedByValue()                      {}

// UnsafeLearnServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LearnServiceServer will
// result in compilation errors.
type UnsafeLearnServiceServer interface {
	mustEmbedUnimplementedLearnServiceServer()
}

func RegisterLearnServiceServer(s grpc.ServiceRegistrar, srv LearnServiceServer) {
	// If the following call panics, it indicates UnimplementedLearnServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LearnService_ServiceDesc, srv)
}

func _LearnService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearnServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearnService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearnServiceServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// LearnService_ServiceDesc is the grpc.ServiceDesc for LearnService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LearnService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "puchi.learn.v1.LearnService",
	HandlerType: (*LearnServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _LearnService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "learn/v1/learn.proto",
}
