// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"github.com/puchidemy/puchi-backend/app/learn/internal/biz"
	"github.com/puchidemy/puchi-backend/app/learn/internal/conf"
	"github.com/puchidemy/puchi-backend/app/learn/internal/data"
	"github.com/puchidemy/puchi-backend/app/learn/internal/server"
	"github.com/puchidemy/puchi-backend/app/learn/internal/service"
	"github.com/puchidemy/puchi-backend/pkg/auth"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confAuth *conf.Auth, learn *conf.Learn, sessionValidator *auth.SessionValidator, logger *slog.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	pool := dataData.Pool
	guestRepo := data.NewGuestRepo(pool)
	progressRepo := data.NewProgressRepo(pool)
	curriculumRepo := data.NewCurriculumRepo(pool)
	storyRepo := data.NewStoryRepo(pool)
	attemptRepo := data.NewAttemptRepo(pool)
	natsLessonEventPublisher, cleanup2, err := data.NewNATSLessonEventPublisher(confData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	transactionManager := data.NewTransactionManager(pool)
	learnUsecase := biz.NewLearnUsecase(guestRepo, progressRepo, curriculumRepo, storyRepo, attemptRepo, natsLessonEventPublisher, transactionManager)
	learnService := service.NewLearnService(learnUsecase, learn)
	grpcServer := server.NewGRPCServer(confServer, learnService)
	httpServer := server.NewHTTPServer(confServer, confAuth, learn, sessionValidator, learnService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
