// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"github.com/puchidemy/puchi-backend/app/learn/internal/biz"
	"github.com/puchidemy/puchi-backend/app/learn/internal/conf"
	"github.com/puchidemy/puchi-backend/app/learn/internal/data"
	"github.com/puchidemy/puchi-backend/app/learn/internal/server"
	"github.com/puchidemy/puchi-backend/app/learn/internal/service"
	"github.com/puchidemy/puchi-backend/pkg/auth"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confAuth *conf.Auth, sessionValidator *auth.SessionValidator, logger *slog.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	pool := dataData.Pool
	learnUsecase := biz.NewLearnUsecase(pool)
	learnService := service.NewLearnService(learnUsecase)
	grpcServer := server.NewGRPCServer(confServer, learnService)
	httpServer := server.NewHTTPServer(confServer, confAuth, sessionValidator, learnService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
