// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: social/v1/social.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationSocialServiceFollow = "/puchi.user.social.v1.SocialService/Follow"
const OperationSocialServiceUnfollow = "/puchi.user.social.v1.SocialService/Unfollow"

type SocialServiceHTTPServer interface {
	Follow(context.Context, *FollowRequest) (*emptypb.Empty, error)
	Unfollow(context.Context, *UnfollowRequest) (*emptypb.Empty, error)
}

func RegisterSocialServiceHTTPServer(s *http.Server, srv SocialServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/social/follow", _SocialService_Follow0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/social/follow/{following_id}", _SocialService_Unfollow0_HTTP_Handler(srv))
}

func _SocialService_Follow0_HTTP_Handler(srv SocialServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FollowRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSocialServiceFollow)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Follow(ctx, req.(*FollowRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _SocialService_Unfollow0_HTTP_Handler(srv SocialServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UnfollowRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSocialServiceUnfollow)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Unfollow(ctx, req.(*UnfollowRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type SocialServiceHTTPClient interface {
	Follow(ctx context.Context, req *FollowRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	Unfollow(ctx context.Context, req *UnfollowRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type SocialServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSocialServiceHTTPClient(client *http.Client) SocialServiceHTTPClient {
	return &SocialServiceHTTPClientImpl{client}
}

func (c *SocialServiceHTTPClientImpl) Follow(ctx context.Context, in *FollowRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/social/follow"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSocialServiceFollow),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SocialServiceHTTPClientImpl) Unfollow(ctx context.Context, in *UnfollowRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/social/follow/{following_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSocialServiceUnfollow),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
