// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"github.com/puchidemy/puchi-backend/app/auth/internal/biz"
	"github.com/puchidemy/puchi-backend/app/auth/internal/conf"
	"github.com/puchidemy/puchi-backend/app/auth/internal/data"
	"github.com/puchidemy/puchi-backend/app/auth/internal/server"
	"github.com/puchidemy/puchi-backend/app/auth/internal/service"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, logger *slog.Logger) (*kratos.App, func(), error) {
	grpcServer := server.NewGRPCServer(confServer)
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData)
	sessionRepo := data.NewSessionRepo(dataData)
	tokenConfig, err := NewTokenConfig(auth)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tokenUsecase := biz.NewTokenUsecase(tokenConfig)
	authUsecase := biz.NewAuthUsecase(userRepo, sessionRepo, tokenUsecase)
	authService := service.NewAuthService(authUsecase, tokenUsecase)
	magicLinkRepo := data.NewMagicLinkRepo(dataData)
	magicLinkUsecase := biz.NewMagicLinkUsecase(magicLinkRepo, userRepo, sessionRepo, tokenUsecase)
	magicLinkService := service.NewMagicLinkService(magicLinkUsecase)
	totpRepo := data.NewTOTPRepo(dataData)
	v := NewEncryptionKey()
	mfaUsecase := biz.NewMFAUsecase(totpRepo, v)
	mfaService := service.NewMFAService(mfaUsecase, tokenUsecase)
	httpServer := server.NewHTTPServer(confServer, auth, authService, magicLinkService, mfaService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
