server:
  http:
    addr: "0.0.0.0:8080"
    timeout: "30s"
  grpc:
    addr: "0.0.0.0:9090"
    timeout: "30s"

data:
  database:
    driver: postgres
    source: "postgres://puchi:puchi-db-prod@192.168.100.201:30433/puchi?sslmode=disable&search_path=auth"
  valkey:
    addr: "127.0.0.1:6379"
    password: ""
    db: 0
    pool_size: 10
  nats:
    url: ""

auth:
  issuer: "https://api.puchi.io.vn"
  key_id: "2026-07-17-prod-1"
  private_key_path: "configs/private.pem"
  access_token_ttl: 900
  refresh_token_ttl: 2592000
  cors_allowed_origins:
    - "https://puchi.io.vn"
    - "http://localhost:3000"
    - "http://localhost:3001"
