// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: social/v1/social.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowingId   string                 `protobuf:"bytes,1,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_social_v1_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{0}
}

func (x *FollowRequest) GetFollowingId() string {
	if x != nil {
		return x.FollowingId
	}
	return ""
}

type UnfollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowingId   string                 `protobuf:"bytes,1,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowRequest) Reset() {
	*x = UnfollowRequest{}
	mi := &file_social_v1_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowRequest) ProtoMessage() {}

func (x *UnfollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowRequest.ProtoReflect.Descriptor instead.
func (*UnfollowRequest) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{1}
}

func (x *UnfollowRequest) GetFollowingId() string {
	if x != nil {
		return x.FollowingId
	}
	return ""
}

type ListFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageToken     *string                `protobuf:"bytes,1,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowingRequest) Reset() {
	*x = ListFollowingRequest{}
	mi := &file_social_v1_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowingRequest) ProtoMessage() {}

func (x *ListFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowingRequest.ProtoReflect.Descriptor instead.
func (*ListFollowingRequest) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{2}
}

func (x *ListFollowingRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

func (x *ListFollowingRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListFollowersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageToken     *string                `protobuf:"bytes,1,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowersRequest) Reset() {
	*x = ListFollowersRequest{}
	mi := &file_social_v1_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowersRequest) ProtoMessage() {}

func (x *ListFollowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowersRequest.ProtoReflect.Descriptor instead.
func (*ListFollowersRequest) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{3}
}

func (x *ListFollowersRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

func (x *ListFollowersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersRequest) Reset() {
	*x = SearchUsersRequest{}
	mi := &file_social_v1_social_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRequest) ProtoMessage() {}

func (x *SearchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersRequest) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{4}
}

func (x *SearchUsersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SocialUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Level         int32                  `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	Streak        int32                  `protobuf:"varint,7,opt,name=streak,proto3" json:"streak,omitempty"`
	IsFollowing   bool                   `protobuf:"varint,8,opt,name=is_following,json=isFollowing,proto3" json:"is_following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocialUser) Reset() {
	*x = SocialUser{}
	mi := &file_social_v1_social_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocialUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialUser) ProtoMessage() {}

func (x *SocialUser) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialUser.ProtoReflect.Descriptor instead.
func (*SocialUser) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{5}
}

func (x *SocialUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SocialUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SocialUser) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *SocialUser) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *SocialUser) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *SocialUser) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *SocialUser) GetStreak() int32 {
	if x != nil {
		return x.Streak
	}
	return 0
}

func (x *SocialUser) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

type SocialUserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SocialUser          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocialUserList) Reset() {
	*x = SocialUserList{}
	mi := &file_social_v1_social_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocialUserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialUserList) ProtoMessage() {}

func (x *SocialUserList) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialUserList.ProtoReflect.Descriptor instead.
func (*SocialUserList) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{6}
}

func (x *SocialUserList) GetItems() []*SocialUser {
	if x != nil {
		return x.Items
	}
	return nil
}

type LeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	WeeklyXp      int32                  `protobuf:"varint,6,opt,name=weekly_xp,json=weeklyXp,proto3" json:"weekly_xp,omitempty"`
	IsCurrentUser bool                   `protobuf:"varint,7,opt,name=is_current_user,json=isCurrentUser,proto3" json:"is_current_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_social_v1_social_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{7}
}

func (x *LeaderboardEntry) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *LeaderboardEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LeaderboardEntry) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LeaderboardEntry) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *LeaderboardEntry) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *LeaderboardEntry) GetWeeklyXp() int32 {
	if x != nil {
		return x.WeeklyXp
	}
	return 0
}

func (x *LeaderboardEntry) GetIsCurrentUser() bool {
	if x != nil {
		return x.IsCurrentUser
	}
	return false
}

type LeaderboardList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*LeaderboardEntry    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardList) Reset() {
	*x = LeaderboardList{}
	mi := &file_social_v1_social_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardList) ProtoMessage() {}

func (x *LeaderboardList) ProtoReflect() protoreflect.Message {
	mi := &file_social_v1_social_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardList.ProtoReflect.Descriptor instead.
func (*LeaderboardList) Descriptor() ([]byte, []int) {
	return file_social_v1_social_proto_rawDescGZIP(), []int{8}
}

func (x *LeaderboardList) GetItems() []*LeaderboardEntry {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_social_v1_social_proto protoreflect.FileDescriptor

const file_social_v1_social_proto_rawDesc = "" +
	"\n" +
	"\x16social/v1/social.proto\x12\x14puchi.core.social.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"2\n" +
	"\rFollowRequest\x12!\n" +
	"\ffollowing_id\x18\x01 \x01(\tR\vfollowingId\"4\n" +
	"\x0fUnfollowRequest\x12!\n" +
	"\ffollowing_id\x18\x01 \x01(\tR\vfollowingId\"f\n" +
	"\x14ListFollowingRequest\x12\"\n" +
	"\n" +
	"page_token\x18\x01 \x01(\tH\x00R\tpageToken\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSizeB\r\n" +
	"\v_page_token\"f\n" +
	"\x14ListFollowersRequest\x12\"\n" +
	"\n" +
	"page_token\x18\x01 \x01(\tH\x00R\tpageToken\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSizeB\r\n" +
	"\v_page_token\"G\n" +
	"\x12SearchUsersRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\xe4\x01\n" +
	"\n" +
	"SocialUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\x12\x14\n" +
	"\x05level\x18\x06 \x01(\x05R\x05level\x12\x16\n" +
	"\x06streak\x18\a \x01(\x05R\x06streak\x12!\n" +
	"\fis_following\x18\b \x01(\bR\visFollowing\"H\n" +
	"\x0eSocialUserList\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .puchi.core.social.v1.SocialUserR\x05items\"\xd5\x01\n" +
	"\x10LeaderboardEntry\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12\x1b\n" +
	"\tweekly_xp\x18\x06 \x01(\x05R\bweeklyXp\x12&\n" +
	"\x0fis_current_user\x18\a \x01(\bR\risCurrentUser\"O\n" +
	"\x0fLeaderboardList\x12<\n" +
	"\x05items\x18\x01 \x03(\v2&.puchi.core.social.v1.LeaderboardEntryR\x05items2\xdc\x05\n" +
	"\rSocialService\x12c\n" +
	"\x06Follow\x12#.puchi.core.social.v1.FollowRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/social/follow\x12s\n" +
	"\bUnfollow\x12%.puchi.core.social.v1.UnfollowRequest\x1a\x16.google.protobuf.Empty\"(\x82\xd3\xe4\x93\x02\"* /v1/social/follow/{following_id}\x12\x7f\n" +
	"\rListFollowing\x12*.puchi.core.social.v1.ListFollowingRequest\x1a$.puchi.core.social.v1.SocialUserList\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/social/following\x12\x7f\n" +
	"\rListFollowers\x12*.puchi.core.social.v1.ListFollowersRequest\x1a$.puchi.core.social.v1.SocialUserList\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/social/followers\x12x\n" +
	"\vSearchUsers\x12(.puchi.core.social.v1.SearchUsersRequest\x1a$.puchi.core.social.v1.SocialUserList\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/social/search\x12u\n" +
	"\x14GetWeeklyLeaderboard\x12\x16.google.protobuf.Empty\x1a%.puchi.core.social.v1.LeaderboardList\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/social/leaderboardBi\n" +
	"\x1aio.grpc.examples.social.v1B\vSocialProtoP\x01Z<github.com/puchidemy/puchi-backend/app/core/api/social/v1;v1b\x06proto3"

var (
	file_social_v1_social_proto_rawDescOnce sync.Once
	file_social_v1_social_proto_rawDescData []byte
)

func file_social_v1_social_proto_rawDescGZIP() []byte {
	file_social_v1_social_proto_rawDescOnce.Do(func() {
		file_social_v1_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_social_v1_social_proto_rawDesc), len(file_social_v1_social_proto_rawDesc)))
	})
	return file_social_v1_social_proto_rawDescData
}

var file_social_v1_social_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_social_v1_social_proto_goTypes = []any{
	(*FollowRequest)(nil),        // 0: puchi.core.social.v1.FollowRequest
	(*UnfollowRequest)(nil),      // 1: puchi.core.social.v1.UnfollowRequest
	(*ListFollowingRequest)(nil), // 2: puchi.core.social.v1.ListFollowingRequest
	(*ListFollowersRequest)(nil), // 3: puchi.core.social.v1.ListFollowersRequest
	(*SearchUsersRequest)(nil),   // 4: puchi.core.social.v1.SearchUsersRequest
	(*SocialUser)(nil),           // 5: puchi.core.social.v1.SocialUser
	(*SocialUserList)(nil),       // 6: puchi.core.social.v1.SocialUserList
	(*LeaderboardEntry)(nil),     // 7: puchi.core.social.v1.LeaderboardEntry
	(*LeaderboardList)(nil),      // 8: puchi.core.social.v1.LeaderboardList
	(*emptypb.Empty)(nil),        // 9: google.protobuf.Empty
}
var file_social_v1_social_proto_depIdxs = []int32{
	5, // 0: puchi.core.social.v1.SocialUserList.items:type_name -> puchi.core.social.v1.SocialUser
	7, // 1: puchi.core.social.v1.LeaderboardList.items:type_name -> puchi.core.social.v1.LeaderboardEntry
	0, // 2: puchi.core.social.v1.SocialService.Follow:input_type -> puchi.core.social.v1.FollowRequest
	1, // 3: puchi.core.social.v1.SocialService.Unfollow:input_type -> puchi.core.social.v1.UnfollowRequest
	2, // 4: puchi.core.social.v1.SocialService.ListFollowing:input_type -> puchi.core.social.v1.ListFollowingRequest
	3, // 5: puchi.core.social.v1.SocialService.ListFollowers:input_type -> puchi.core.social.v1.ListFollowersRequest
	4, // 6: puchi.core.social.v1.SocialService.SearchUsers:input_type -> puchi.core.social.v1.SearchUsersRequest
	9, // 7: puchi.core.social.v1.SocialService.GetWeeklyLeaderboard:input_type -> google.protobuf.Empty
	9, // 8: puchi.core.social.v1.SocialService.Follow:output_type -> google.protobuf.Empty
	9, // 9: puchi.core.social.v1.SocialService.Unfollow:output_type -> google.protobuf.Empty
	6, // 10: puchi.core.social.v1.SocialService.ListFollowing:output_type -> puchi.core.social.v1.SocialUserList
	6, // 11: puchi.core.social.v1.SocialService.ListFollowers:output_type -> puchi.core.social.v1.SocialUserList
	6, // 12: puchi.core.social.v1.SocialService.SearchUsers:output_type -> puchi.core.social.v1.SocialUserList
	8, // 13: puchi.core.social.v1.SocialService.GetWeeklyLeaderboard:output_type -> puchi.core.social.v1.LeaderboardList
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_social_v1_social_proto_init() }
func file_social_v1_social_proto_init() {
	if File_social_v1_social_proto != nil {
		return
	}
	file_social_v1_social_proto_msgTypes[2].OneofWrappers = []any{}
	file_social_v1_social_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_social_v1_social_proto_rawDesc), len(file_social_v1_social_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_social_v1_social_proto_goTypes,
		DependencyIndexes: file_social_v1_social_proto_depIdxs,
		MessageInfos:      file_social_v1_social_proto_msgTypes,
	}.Build()
	File_social_v1_social_proto = out.File
	file_social_v1_social_proto_goTypes = nil
	file_social_v1_social_proto_depIdxs = nil
}
