server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  supertokens:
    connection_uri: "http://localhost:30567"
    api_key: "change-in-production-please"
    cookie_domain: "localhost"
    cookie_secure: false
  public_paths:
    - /v1/health
    - /v1/healthz
