server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    source: "postgresql://puchi:puchi-db-prod@192.168.100.201:30433/puchi?sslmode=disable"
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  auth_service_url: "http://localhost:8080"
  public_paths:
    - /v1/health
    - /v1/healthz
