// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: notification/v1/notification.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationNotificationServiceGetPreferences = "/puchi.notification.v1.NotificationService/GetPreferences"
const OperationNotificationServiceUpdatePreferences = "/puchi.notification.v1.NotificationService/UpdatePreferences"

type NotificationServiceHTTPServer interface {
	GetPreferences(context.Context, *GetPreferencesRequest) (*Preferences, error)
	UpdatePreferences(context.Context, *UpdatePreferencesRequest) (*Preferences, error)
}

func RegisterNotificationServiceHTTPServer(s *http.Server, srv NotificationServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/notifications/preferences", _NotificationService_GetPreferences0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/notifications/preferences", _NotificationService_UpdatePreferences0_HTTP_Handler(srv))
}

func _NotificationService_GetPreferences0_HTTP_Handler(srv NotificationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPreferencesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotificationServiceGetPreferences)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPreferences(ctx, req.(*GetPreferencesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Preferences)
		return ctx.Result(200, reply)
	}
}

func _NotificationService_UpdatePreferences0_HTTP_Handler(srv NotificationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdatePreferencesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotificationServiceUpdatePreferences)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdatePreferences(ctx, req.(*UpdatePreferencesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Preferences)
		return ctx.Result(200, reply)
	}
}

type NotificationServiceHTTPClient interface {
	GetPreferences(ctx context.Context, req *GetPreferencesRequest, opts ...http.CallOption) (rsp *Preferences, err error)
	UpdatePreferences(ctx context.Context, req *UpdatePreferencesRequest, opts ...http.CallOption) (rsp *Preferences, err error)
}

type NotificationServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewNotificationServiceHTTPClient(client *http.Client) NotificationServiceHTTPClient {
	return &NotificationServiceHTTPClientImpl{client}
}

func (c *NotificationServiceHTTPClientImpl) GetPreferences(ctx context.Context, in *GetPreferencesRequest, opts ...http.CallOption) (*Preferences, error) {
	var out Preferences
	pattern := "/v1/notifications/preferences"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationNotificationServiceGetPreferences),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *NotificationServiceHTTPClientImpl) UpdatePreferences(ctx context.Context, in *UpdatePreferencesRequest, opts ...http.CallOption) (*Preferences, error) {
	var out Preferences
	pattern := "/v1/notifications/preferences"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationNotificationServiceUpdatePreferences),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
