// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: notification/v1/notification.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Preferences struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	UserId          string                  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PushEnabled     bool                    `protobuf:"varint,2,opt,name=push_enabled,json=pushEnabled,proto3" json:"push_enabled,omitempty"`
	EmailEnabled    bool                    `protobuf:"varint,3,opt,name=email_enabled,json=emailEnabled,proto3" json:"email_enabled,omitempty"`
	StreakReminder  bool                    `protobuf:"varint,4,opt,name=streak_reminder,json=streakReminder,proto3" json:"streak_reminder,omitempty"`
	FriendActivity  bool                    `protobuf:"varint,5,opt,name=friend_activity,json=friendActivity,proto3" json:"friend_activity,omitempty"`
	Promotions      bool                    `protobuf:"varint,6,opt,name=promotions,proto3" json:"promotions,omitempty"`
	QuietHoursStart *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=quiet_hours_start,json=quietHoursStart,proto3" json:"quiet_hours_start,omitempty"`
	QuietHoursEnd   *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=quiet_hours_end,json=quietHoursEnd,proto3" json:"quiet_hours_end,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Preferences) Reset() {
	*x = Preferences{}
	mi := &file_notification_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Preferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Preferences) ProtoMessage() {}

func (x *Preferences) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Preferences.ProtoReflect.Descriptor instead.
func (*Preferences) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *Preferences) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Preferences) GetPushEnabled() bool {
	if x != nil {
		return x.PushEnabled
	}
	return false
}

func (x *Preferences) GetEmailEnabled() bool {
	if x != nil {
		return x.EmailEnabled
	}
	return false
}

func (x *Preferences) GetStreakReminder() bool {
	if x != nil {
		return x.StreakReminder
	}
	return false
}

func (x *Preferences) GetFriendActivity() bool {
	if x != nil {
		return x.FriendActivity
	}
	return false
}

func (x *Preferences) GetPromotions() bool {
	if x != nil {
		return x.Promotions
	}
	return false
}

func (x *Preferences) GetQuietHoursStart() *wrapperspb.StringValue {
	if x != nil {
		return x.QuietHoursStart
	}
	return nil
}

func (x *Preferences) GetQuietHoursEnd() *wrapperspb.StringValue {
	if x != nil {
		return x.QuietHoursEnd
	}
	return nil
}

type GetPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesRequest) Reset() {
	*x = GetPreferencesRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesRequest) ProtoMessage() {}

func (x *GetPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesRequest.ProtoReflect.Descriptor instead.
func (*GetPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *GetPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdatePreferencesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PushEnabled    *wrapperspb.BoolValue  `protobuf:"bytes,2,opt,name=push_enabled,json=pushEnabled,proto3" json:"push_enabled,omitempty"`
	StreakReminder *wrapperspb.BoolValue  `protobuf:"bytes,4,opt,name=streak_reminder,json=streakReminder,proto3" json:"streak_reminder,omitempty"`
	FriendActivity *wrapperspb.BoolValue  `protobuf:"bytes,5,opt,name=friend_activity,json=friendActivity,proto3" json:"friend_activity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdatePreferencesRequest) Reset() {
	*x = UpdatePreferencesRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesRequest) ProtoMessage() {}

func (x *UpdatePreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdatePreferencesRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePreferencesRequest) GetPushEnabled() *wrapperspb.BoolValue {
	if x != nil {
		return x.PushEnabled
	}
	return nil
}

func (x *UpdatePreferencesRequest) GetStreakReminder() *wrapperspb.BoolValue {
	if x != nil {
		return x.StreakReminder
	}
	return nil
}

func (x *UpdatePreferencesRequest) GetFriendActivity() *wrapperspb.BoolValue {
	if x != nil {
		return x.FriendActivity
	}
	return nil
}

type SendNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"` // "streak_reminder", "friend_activity", "achievement"
	TemplateId    string                 `protobuf:"bytes,3,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Params        map[string]string      `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{3}
}

func (x *SendNotificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendNotificationRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SendNotificationRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SendNotificationRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type SendNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sent          bool                   `protobuf:"varint,1,opt,name=sent,proto3" json:"sent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{4}
}

func (x *SendNotificationResponse) GetSent() bool {
	if x != nil {
		return x.Sent
	}
	return false
}

var File_notification_v1_notification_proto protoreflect.FileDescriptor

const file_notification_v1_notification_proto_rawDesc = "" +
	"\n" +
	"\"notification/v1/notification.proto\x12\x15puchi.notification.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xf0\x02\n" +
	"\vPreferences\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fpush_enabled\x18\x02 \x01(\bR\vpushEnabled\x12#\n" +
	"\remail_enabled\x18\x03 \x01(\bR\femailEnabled\x12'\n" +
	"\x0fstreak_reminder\x18\x04 \x01(\bR\x0estreakReminder\x12'\n" +
	"\x0ffriend_activity\x18\x05 \x01(\bR\x0efriendActivity\x12\x1e\n" +
	"\n" +
	"promotions\x18\x06 \x01(\bR\n" +
	"promotions\x12H\n" +
	"\x11quiet_hours_start\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\x0fquietHoursStart\x12D\n" +
	"\x0fquiet_hours_end\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\rquietHoursEnd\"0\n" +
	"\x15GetPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xfc\x01\n" +
	"\x18UpdatePreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12=\n" +
	"\fpush_enabled\x18\x02 \x01(\v2\x1a.google.protobuf.BoolValueR\vpushEnabled\x12C\n" +
	"\x0fstreak_reminder\x18\x04 \x01(\v2\x1a.google.protobuf.BoolValueR\x0estreakReminder\x12C\n" +
	"\x0ffriend_activity\x18\x05 \x01(\v2\x1a.google.protobuf.BoolValueR\x0efriendActivity\"\xfe\x01\n" +
	"\x17SendNotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1f\n" +
	"\vtemplate_id\x18\x03 \x01(\tR\n" +
	"templateId\x12R\n" +
	"\x06params\x18\x04 \x03(\v2:.puchi.notification.v1.SendNotificationRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\x18SendNotificationResponse\x12\x12\n" +
	"\x04sent\x18\x01 \x01(\bR\x04sent2\x9f\x03\n" +
	"\x13NotificationService\x12\x89\x01\n" +
	"\x0eGetPreferences\x12,.puchi.notification.v1.GetPreferencesRequest\x1a\".puchi.notification.v1.Preferences\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/notifications/preferences\x12\x92\x01\n" +
	"\x11UpdatePreferences\x12/.puchi.notification.v1.UpdatePreferencesRequest\x1a\".puchi.notification.v1.Preferences\"(\x82\xd3\xe4\x93\x02\":\x01*\x1a\x1d/v1/notifications/preferences\x12g\n" +
	"\x04Send\x12..puchi.notification.v1.SendNotificationRequest\x1a/.puchi.notification.v1.SendNotificationResponseBLZJgithub.com/puchidemy/puchi-backend/app/notification/api/notification/v1;v1b\x06proto3"

var (
	file_notification_v1_notification_proto_rawDescOnce sync.Once
	file_notification_v1_notification_proto_rawDescData []byte
)

func file_notification_v1_notification_proto_rawDescGZIP() []byte {
	file_notification_v1_notification_proto_rawDescOnce.Do(func() {
		file_notification_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_v1_notification_proto_rawDesc), len(file_notification_v1_notification_proto_rawDesc)))
	})
	return file_notification_v1_notification_proto_rawDescData
}

var file_notification_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_notification_v1_notification_proto_goTypes = []any{
	(*Preferences)(nil),              // 0: puchi.notification.v1.Preferences
	(*GetPreferencesRequest)(nil),    // 1: puchi.notification.v1.GetPreferencesRequest
	(*UpdatePreferencesRequest)(nil), // 2: puchi.notification.v1.UpdatePreferencesRequest
	(*SendNotificationRequest)(nil),  // 3: puchi.notification.v1.SendNotificationRequest
	(*SendNotificationResponse)(nil), // 4: puchi.notification.v1.SendNotificationResponse
	nil,                              // 5: puchi.notification.v1.SendNotificationRequest.ParamsEntry
	(*wrapperspb.StringValue)(nil),   // 6: google.protobuf.StringValue
	(*wrapperspb.BoolValue)(nil),     // 7: google.protobuf.BoolValue
}
var file_notification_v1_notification_proto_depIdxs = []int32{
	6, // 0: puchi.notification.v1.Preferences.quiet_hours_start:type_name -> google.protobuf.StringValue
	6, // 1: puchi.notification.v1.Preferences.quiet_hours_end:type_name -> google.protobuf.StringValue
	7, // 2: puchi.notification.v1.UpdatePreferencesRequest.push_enabled:type_name -> google.protobuf.BoolValue
	7, // 3: puchi.notification.v1.UpdatePreferencesRequest.streak_reminder:type_name -> google.protobuf.BoolValue
	7, // 4: puchi.notification.v1.UpdatePreferencesRequest.friend_activity:type_name -> google.protobuf.BoolValue
	5, // 5: puchi.notification.v1.SendNotificationRequest.params:type_name -> puchi.notification.v1.SendNotificationRequest.ParamsEntry
	1, // 6: puchi.notification.v1.NotificationService.GetPreferences:input_type -> puchi.notification.v1.GetPreferencesRequest
	2, // 7: puchi.notification.v1.NotificationService.UpdatePreferences:input_type -> puchi.notification.v1.UpdatePreferencesRequest
	3, // 8: puchi.notification.v1.NotificationService.Send:input_type -> puchi.notification.v1.SendNotificationRequest
	0, // 9: puchi.notification.v1.NotificationService.GetPreferences:output_type -> puchi.notification.v1.Preferences
	0, // 10: puchi.notification.v1.NotificationService.UpdatePreferences:output_type -> puchi.notification.v1.Preferences
	4, // 11: puchi.notification.v1.NotificationService.Send:output_type -> puchi.notification.v1.SendNotificationResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_notification_v1_notification_proto_init() }
func file_notification_v1_notification_proto_init() {
	if File_notification_v1_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_v1_notification_proto_rawDesc), len(file_notification_v1_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_v1_notification_proto_goTypes,
		DependencyIndexes: file_notification_v1_notification_proto_depIdxs,
		MessageInfos:      file_notification_v1_notification_proto_msgTypes,
	}.Build()
	File_notification_v1_notification_proto = out.File
	file_notification_v1_notification_proto_goTypes = nil
	file_notification_v1_notification_proto_depIdxs = nil
}
